### ISSUE TITLE
Incorrect swap\trading COM-ATOM during competition

### ISSUE THREAD

**Issue by mybloomingpath** [tendermint/liquidity#242] opened 2021-05-05 21:57 UTC
Hello Team.

 

## Summary of Bug

Thanks for such a cool product and fun during competition.
I mentioned incorrect balance after "swap" token during competion.
I had balance of ATOM ( 25 tokens) and ( around 630 COM tokens)

Selling 300 COM and trying to buy more atom , in final my ATOM balance became 10. 
COMPETITION WALLET cosmos15pmgwg4ps853q30kyn856mgfzclfr22q8l98d8

## Steps to Reproduce

As there many coplaints form participants that they have no ATOM to continue trading, maybe there is some bug when balance of atom dissappear while trading some pairs of token? 
Please check and correct if that was a bug.
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by dongsam** [comment] 2021-05-05 22:02
Hello, thank you for the report.
May I know the testnet address where the bug occurred? 
Let me analyze the Tx history and then I'll answer.

**Comment by mybloomingpath** [comment] 2021-05-05 22:07
That was https://gravitydex.io/app#/swap  I use KEPLR  for COSMOS wallet testnet  "COMPETITION"

**Comment by dongsam** [comment] 2021-05-05 22:09
I'd appreciate it if you could tell me your wallet address starting with `cosmos1..`

**Comment by mybloomingpath** [comment] 2021-05-05 22:10
I gave it in the issue above :) COMPETITION WALLET cosmos15pmgwg4ps853q30kyn856mgfzclfr22q8l98d8

**Comment by reskyh** [comment] 2021-05-06 01:31
I have problem like that
Can you help me sir ?

> I'd appreciate it if you could tell me your wallet address starting with `cosmos1..`

Can you help me too sir ?
I have a same problem
This my wallet address cosmos1ek238pj99nmdtnaeqt2hakhh2q8cqul0tz6dvg

**Comment by kogisin** [comment] 2021-05-06 02:13
Thanks for your report @mybloomingpath.

In order to debug this, I need to know what exactly happened. From the context you provided above, you had about 25 ATOM and 630 COM coins before you made swap of selling 300 COM to buy X amount of ATOM coins, but your ATOM balance decreased. Am I understanding correctly? 

And, this is your address for the incentivized testnet `cosmos15pmgwg4ps853q30kyn856mgfzclfr22q8l98d8`

**Comment by reskyh** [comment] 2021-05-06 02:20
> Thanks for your report @mybloomingpath.
> 
> In order to debug this, I need to know what exactly happened. From the context you provided above, you had about 25 ATOM and 630 COM coins before you made swap of selling 300 COM to buy X amount of ATOM coins, but your ATOM balance decreased. Am I understanding correctly?
> 
> And, this is your address for the incentivized testnet `cosmos15pmgwg4ps853q30kyn856mgfzclfr22q8l98d8`
> 
> @reskyh Are you experiencing the same or similar issue?

I cant swap or redeem because issue of inslft amount of atom, i try using the gas and i try to change that fee % , still not working
And now i cant do my task anymore

**Comment by kogisin** [comment] 2021-05-06 02:27
@reskyh So your issue is you are unable to swap due to insufficient amount of ATOM?

**Comment by reskyh** [comment] 2021-05-06 02:28
Yes sirr

Pada tanggal Kam, 6 Mei 2021 09.27, JayB ***@***.***> menulis:

**Comment by hallazzang** [comment] 2021-05-06 05:18
@mybloomingpath 
Here's what your action log says:
```
2021-05-05 21:29:07.43783696 +0000 UTC [deposit] height = 28936, accepted coins = 14626861uatom,300000000ucom
```
So you did **deposit** instead of **swap**. That's why your COM and ATOM balances decreased together.
Also you can see `ATOM/COM` pool coin in your wallet.
Hope it helps you.

**Comment by kogisin** [comment] 2021-05-06 05:36
To add on what @hallazzang provided, here is [the transaction hash](https://competition.bharvest.io:1317/cosmos/tx/v1beta1/txs/2A9C35E215CF5CE494BD381F697521FBD82266FACA71F32F826EAD26F38127DE) that you sent for proof. We will close this issue since this is not a bug.

**Comment by mybloomingpath** [comment] 2021-05-06 06:19
Thank you GUYS, and excuse me for troubling you.

**Closed** 2021-05-06 08:12 UTC
